#!/usr/bin/env bash

set -x

: ${WATCH_OPTS:=""}

echo "Running make..."
make $1 >/tmp/before.txt 2>&1
echo "Output of make:"

cat /tmp/before.txt
read -p "Continue? " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
	cp /tmp/before.txt /tmp/after.txt
    
	(sleep 1 && find -L . | entr sh -c "make $1 > /tmp/after.txt 2>&1") &
	watch ${WATCH_OPTS} --color 'diff /tmp/before.txt /tmp/after.txt --unified | colordiff'
	kill -TERM %1 # -$WPID >/dev/null 2>&1 || true
fi
